ProyectoIS2_9/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView

from ProyectoIS2_9 import settings
from .views import IndexView
from ProyectoIS2_9.views import NuestroLoginView


urlpatterns = [

    url(r'^$', IndexView.as_view(), name='index'),

    url(r'^proyectos/', include('proyecto.urls')),

    url(r'^roles/', include('roles_sistema.urls')),

    url(r'^usuarios/', include('usuario.urls')),

    url(r'^clientes/', include('cliente.urls')),

    url(r'^login/$', NuestroLoginView.as_view(template_name='login/login.html',
            redirect_authenticated_user=True), name='login'),

    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', admin.site.urls),

    url(r'^files/', include('db_file_storage.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cliente/urls.py
from django.conf.urls import url

from cliente.views import \
    ClienteListView, ClienteCreateView, ClienteUpdateView, \
    ClientePerfilView, ClienteListJson, ClienteDeleteView, ReporteClientePDF

app_name = 'cliente'
urlpatterns = [
    url(r'^$', ClienteListView.as_view(), name='lista'),
    url(r'^crear/$', ClienteCreateView.as_view(), name='crear'),
    url(r'^list/$', ClienteListJson.as_view(), name='lista_json'),
    url(r'^(?P<cliente_id>\d+)/reporte/$', ReporteClientePDF.as_view(), name='reporte_cliente'),
    url(r'^(?P<cliente_id>\d+)/editar/$', ClienteUpdateView.as_view(), name='editar'),
    url(r'^(?P<cliente_id>\d+)/perfil/$', ClientePerfilView.as_view(), name='ver'),
    url(r'^(?P<cliente_id>\d+)/eliminar/$', ClienteDeleteView.as_view(), name='eliminar'),
]

roles_sistema/urls.py
from django.conf.urls import url
from .views import RolListJson,RolListView,RolCreateView,RolUpdateView,RolPerfilView,RolEliminarView

app_name = 'rol_sistema'
urlpatterns = [
    url(r'^$', RolListView.as_view(), name='lista'),
    url(r'^list/$', RolListJson.as_view(), name='lista_json'),
    url(r'^crear/$', RolCreateView.as_view(), name='crear'),
    url(r'^(?P<rol_id>\d+)/editar/$', RolUpdateView.as_view(), name='editar'),
    url(r'^(?P<rol_id>\d+)/perfil/$', RolPerfilView.as_view(), name='ver'),
    url(r'^(?P<rol_id>\d+)/eliminar/$', RolEliminarView.as_view(), name='eliminar'),
]

roles_sistema/models.py
from django.db import models

# Create your models here.

roles_sistema/forms.py
from crispy_forms.bootstrap import FormActions, AppendedText
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, HTML, Layout, Fieldset, Row, Div, Column
from dal import autocomplete
from django import forms
from django.forms import ModelForm, DateInput, Form
from django.contrib.auth.models import Permission, User
from proyecto.models import RolAdministrativo, Proyecto, Cliente, Usuario

from django.db.models import Q
from django.forms import ModelMultipleChoiceField

class PermisosModelMultipleChoiceField(ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.name

class RolSistemaForm(ModelForm):
    permissions = PermisosModelMultipleChoiceField(
        queryset=Permission.objects.filter(
            Q(content_type__app_label=Proyecto._meta.app_label,content_type__model=Proyecto._meta.model_name, codename='add_proyecto') |
            Q(content_type__app_label=Usuario._meta.app_label,content_type__model=Usuario._meta.model_name) |
            Q(content_type__app_label=RolAdministrativo._meta.app_label,content_type__model=RolAdministrativo._meta.model_name) |
            Q(content_type__app_label=Cliente._meta.app_label,content_type__model=Cliente._meta.model_name)
        ),
        widget=forms.CheckboxSelectMultiple,
        required=True,
        label="Permisos"
    )
    class Meta:
        model = RolAdministrativo
        fields = ['name','permissions']


    def __init__(self, *args, **kwargs):
        self.success_url = kwargs.pop('success_url')
        super(RolSistemaForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        layout = [
            'name',
            'permissions',
            FormActions(
                Submit('guardar', 'Guardar'),
                HTML('<a class="btn btn-default" href={}>Cancelar</a>'.format(self.success_url)),
            ),

        ]
        self.helper.layout = Layout(*layout)

roles_sistema/views.py
from django.http import HttpResponseForbidden
from django.views.generic import TemplateView, DetailView, UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse,reverse_lazy
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.http import HttpResponseRedirect
from datos_de_prueba.funciones import ROL_ADMINISTRADOR_NOMBRE
from roles_sistema.forms import RolSistemaForm
from proyecto.models import RolAdministrativo
from ProyectoIS2_9.utils import cualquier_permiso

class RolListView(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    template_name = 'change_list.html'
    permission_required = (
        'proyecto.add_roladministrativo', 'proyecto.change_roladministrativo', 'proyecto.delete_roladministrativo'
    )
    permission_denied_message = 'No tiene permiso para ver los roles.'

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def has_permission(self):
        """
        Se sobreescribe para que si tiene al menos uno de los permisos listados en permission_required, tiene permisos
        :return:
        """
        return cualquier_permiso(self.request.user, self.get_permission_required())

    def get_context_data(self, **kwargs):
        context = super(RolListView, self).get_context_data(**kwargs)
        context['titulo'] = 'Lista de Roles Administrativos'
        context['crear_button'] = self.request.user.has_perm('proyecto.add_roladministrativo')
        context['crear_url'] = reverse('rol_sistema:crear')
        context['crear_button_text'] = 'Nuevo Rol'

        # datatables
        context['nombres_columnas'] = ['id', 'Nombre']
        context['order'] = [1, "asc"]
        context['datatable_row_link'] = reverse('rol_sistema:ver', args=(1,))  # pasamos inicialmente el id 1
        context['list_json'] = reverse('rol_sistema:lista_json')

        #Breadcrumbs
        context['breadcrumb'] = [{'nombre':'Inicio', 'url':'/'},
                   {'nombre':'Roles Administrativos', 'url': '#'},
                   ]



        return context

class RolListJson(LoginRequiredMixin, PermissionRequiredMixin, BaseDatatableView):
    model = RolAdministrativo
    columns = ['id', 'name']
    order_columns = ['id', 'name']
    max_display_length = 100
    permission_required = (
        'proyecto.add_roladministrativo', 'proyecto.change_roladministrativo', 'proyecto.delete_roladministrativo'
    )
    permission_denied_message = 'No tiene permiso para ver los roles.'

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def has_permission(self):
        return cualquier_permiso(self.request.user, self.get_permission_required())

class RolCreateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    model = RolAdministrativo
    template_name = "change_form.html"
    form_class = RolSistemaForm
    permission_required = 'proyecto.add_roladministrativo'
    permission_denied_message = 'No tiene permiso para Crear nuevos proyectos.'

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def get_success_message(self, cleaned_data):
        return "Rol '{}' creado exitosamente.".format(cleaned_data['name'])

    def get_success_url(self):
        return reverse('rol_sistema:lista')

    def get_form_kwargs(self):
        kwargs = super(RolCreateView, self).get_form_kwargs()
        kwargs.update({
            'success_url': reverse('rol_sistema:lista'),
        })
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(RolCreateView, self).get_context_data(**kwargs)
        context['titulo'] = 'Roles Administrativos'
        context['titulo_form_crear'] = 'Insertar Datos del Nuevo Rol Administrativo'

        # Breadcrumbs
        context['breadcrumb'] = [{'nombre': 'Inicio', 'url': '/'},
                                 {'nombre': 'Roles Administrativos', 'url': reverse('rol_sistema:lista')},
                                 {'nombre': 'Crear', 'url': '#'}
                                 ]

        return context

class RolUpdateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, UpdateView):
    model = RolAdministrativo
    form_class = RolSistemaForm
    context_object_name = 'rol'
    template_name = 'change_form.html'
    pk_url_kwarg = 'rol_id'
    permission_required = 'proyecto.change_roladministrativo'
    permission_denied_message = 'No tiene permiso para Editar Roles.'

    def has_permission(self):
        """
        Se sobreescribe la comprobacion de permisos para denegar el acceso si el usuario posee el rol administrativo a editar
        :return:
        """
        try:
            rol_a_editar = self.get_object()
            roles_usuario = RolAdministrativo.objects.filter(user=self.request.user)
            if(rol_a_editar in roles_usuario or rol_a_editar.name == ROL_ADMINISTRADOR_NOMBRE):
                return False
        except RolAdministrativo.DoesNotExist:
            return super(RolUpdateView, self).has_permission()
        except:
            return super(RolUpdateView, self).has_permission()
        else:
            return super(RolUpdateView, self).has_permission()

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def get_success_message(self, cleaned_data):
        return "Rol Administrativo '{}' editado exitosamente.".format(cleaned_data['name'])

    def get_success_url(self):
        return reverse('rol_sistema:ver', kwargs=self.kwargs)

    def get_form_kwargs(self):
        kwargs = super(RolUpdateView, self).get_form_kwargs()

        kwargs.update({
            'success_url': self.get_success_url(),
        })
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(RolUpdateView, self).get_context_data(**kwargs)
        context['titulo'] = 'Editar Rol Administrativo'
        context['titulo_form_editar'] = 'Datos del Rol'
        context['titulo_form_editar_nombre'] = context[RolUpdateView.context_object_name].name

        # Breadcrumbs
        context['breadcrumb'] = [{'nombre': 'Inicio', 'url': '/'},
                                 {'nombre': 'Roles Administrativos', 'url': reverse('rol_sistema:lista')},
                                 {'nombre': context['rol'].name, 'url': reverse('rol_sistema:ver',kwargs=self.kwargs)},
                                 {'nombre': 'Editar', 'url': '#'},
                                 ]

        return context

class RolPerfilView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = RolAdministrativo
    context_object_name = 'rol'
    template_name = 'roles_sistema/change_perfil.html'
    pk_url_kwarg = 'rol_id'
    permission_required = ('proyecto.add_roladministrativo','proyecto.change_roladministrativo','proyecto.delete_roladministrativo')
    permission_denied_message = 'No tiene permiso para ver Proyectos.'

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def has_permission(self):
        return cualquier_permiso(self.request.user, self.get_permission_required())

    def get_context_data(self, **kwargs):
        context = super(RolPerfilView, self).get_context_data(**kwargs)
        context['titulo'] = 'Perfil del Rol Administrativo'
        context['breadcrumb'] = [{'nombre': 'Inicio', 'url': '/'},
                                 {'nombre': 'Roles Administrativos', 'url': reverse('rol_sistema:lista')},
                                 {'nombre': context['rol'].name, 'url': '#'}
                                 ]
        rol = self.get_object()
        context['es_rol_administrador'] = rol.name == ROL_ADMINISTRADOR_NOMBRE

        return context


class RolEliminarView(LoginRequiredMixin, PermissionRequiredMixin,SuccessMessageMixin, DeleteView):
    model = RolAdministrativo
    context_object_name = 'rol'
    template_name = 'roles_sistema/eliminar_rol.html'
    pk_url_kwarg = 'rol_id'
    permission_required = 'proyecto.delete_roladministrativo'
    permission_denied_message = 'No tiene permiso para eliminar el rol.'
    success_url = reverse_lazy('rol_sistema:lista')

    def has_permission(self):
        """
        Se sobreescribe la comprobacion de permisos para denegar el acceso si hay algun usuario que posea el rol administrativo a eliminar o es el rol administrador
        :return:
        """
        try:
            rol_a_eliminar = self.get_object()
            if(not self.eliminable() or rol_a_eliminar.name == ROL_ADMINISTRADOR_NOMBRE):
                return False
        except RolAdministrativo.DoesNotExist:
            return super(RolEliminarView, self).has_permission()
        except:
            return super(RolEliminarView, self).has_permission()
        else:
            return super(RolEliminarView, self).has_permission()

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def get_success_message(self, cleaned_data):
        return "Rol Administrativo  eliminado exitosamente."

    def get_context_data(self, **kwargs):
        context = super(RolEliminarView, self).get_context_data(**kwargs)
        context['titulo'] = 'Eliminar Rol'
        context['breadcrumb'] = [{'nombre': 'Inicio', 'url': '/'},
                                 {'nombre': 'Roles Administrativos', 'url': reverse('rol_sistema:lista')},
                                 {'nombre': context['rol'].name,
                                  'url': reverse('rol_sistema:ver', kwargs=self.kwargs)},
                                 {'nombre': 'Eliminar', 'url': '#'}, ]
        context['eliminable'] = self.eliminable()
        return context

    def eliminable(self):
        return not self.get_object().user_set.all()

    def post(self, request, *args, **kwargs):
        if self.eliminable():

roles_sistema/templates/roles_sistema/change_perfil.html
{% extends 'layout/layout.html' %}
{% load static %}


{% block content %}
    {% block titulo %}
        <div class="bg-light lter b-b wrapper-md col-md-12">
            <h1 class="m-n font-thin h3 col-lg-6">{{ titulo }}</h1>
            <br>
        </div>
    {% endblock %}

    {% block breadcrumbs %}
        {{ block.super }}
    {% endblock %}

  <div class="wrapper-md">
    <div class="well m-t bg-light lt">
      <div class="row">

        <div class="col-xs-4">
          <h4>{{ rol.name }}</h4>
          <p>
              <strong>Nombre del Rol: </strong>   {{ rol.name|default_if_none:"" }}<br><br>
          </p>
        </div>

        <div class="col-xs-6">
          <h4>&nbsp;</h4>
          <p>
              <strong>Permisos: </strong>  <br>
              <ul>
                {% for permisos in rol.permissions.all %}
                    <li>{{  permisos.name }}</li>
                {% endfor %}
              </ul>
              <br>
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
            <!-- Se comprueba si tiene permiso para editar y que el usuario no posea dicho rol y si el rol no es el rol administrador -->
            {% if perms.proyecto.change_roladministrativo and not rol.group_ptr in user.groups.all and not es_rol_administrador%}
                <a href="{% url 'rol_sistema:editar' rol.id %}">
                  <button class="btn m-b-xs btn-default btn-addon ">
                    <i class="fa fa-pencil"></i>
                    Editar
                  </button>
                </a>
            {% endif %}
            <!-- Se comprueba si tiene permiso para eliminar y si el rol no es el rol administrador y si ningun usuario utiliza el rol -->
            {% if perms.proyecto.delete_roladministrativo and not es_rol_administrador and not rol.user_set.all%}
                <a href="{% url 'rol_sistema:eliminar' rol.id %}">
                  <button class="btn m-b-xs btn-danger btn-addon ">
                    <i class="fa fa-trash-o"></i>
                    Eliminar
                  </button>
                </a>
            {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

roles_sistema/templates/roles_sistema/eliminar_rol.html
{% extends 'layout/layout.html' %}

{% block content %}
    {% block titulo %}
        <div class="bg-light lter b-b wrapper-md col-md-12">
            <h1 class="m-n font-thin h3 col-lg-6">{{ titulo }}</h1>
        </div>
    {% endblock %}

    {% block breadcrumbs %}
        {{ block.super }}
    {% endblock %}

    <div class="wrapper-md">
        <div class="well m-t bg-light lt">
            {% if eliminable %}
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-xs-12">
                            <p>Seguro que quiere eliminar el rol "{{ rol }}"?</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <button type="submit" class="btn m-b-xs btn-danger btn-addon">
                                <i class="fa fa-check"></i>
                                Confirmar
                            </button>
                            <a href="{% url 'rol_sistema:ver' rol.id %}">
                                <button type="button" class="btn m-b-xs btn-default btn-addon">
                                    <i class="fa fa-close"></i>
                                    Cancelar
                                </button>
                            </a>
                        </div>
                    </div>
                </form>
            {% else %}
                <div class="row">
                    <div class="col-xs-12">
                        <p>
                            No se puede eliminar el rol "{{ rol.name }}" por que tiene
                            vinculado al menos un usuario
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <a href="{% url 'rol_sistema:ver' rol.id %}">
                            <button type="button" class="btn m-b-xs btn-default btn-addon">
                                <i class="fa fa-check"></i>
                                Volver
                            </button>
                        </a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}