ProyectoIS2_9/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView

from ProyectoIS2_9 import settings
from .views import IndexView
from ProyectoIS2_9.views import NuestroLoginView


urlpatterns = [

    url(r'^$', IndexView.as_view(), name='index'),

    url(r'^proyectos/', include('proyecto.urls')),

    url(r'^roles/', include('roles_sistema.urls')),

    url(r'^usuarios/', include('usuario.urls')),

    url(r'^clientes/', include('cliente.urls')),

    url(r'^login/$', NuestroLoginView.as_view(template_name='login/login.html',
            redirect_authenticated_user=True), name='login'),

    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', admin.site.urls),

    url(r'^files/', include('db_file_storage.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cliente/urls.py
from django.conf.urls import url

from cliente.views import \
    ClienteListView, ClienteCreateView, ClienteUpdateView, \
    ClientePerfilView, ClienteListJson, ClienteDeleteView, ReporteClientePDF

app_name = 'cliente'
urlpatterns = [
    url(r'^$', ClienteListView.as_view(), name='lista'),
    url(r'^crear/$', ClienteCreateView.as_view(), name='crear'),
    url(r'^list/$', ClienteListJson.as_view(), name='lista_json'),
    url(r'^(?P<cliente_id>\d+)/reporte/$', ReporteClientePDF.as_view(), name='reporte_cliente'),
    url(r'^(?P<cliente_id>\d+)/editar/$', ClienteUpdateView.as_view(), name='editar'),
    url(r'^(?P<cliente_id>\d+)/perfil/$', ClientePerfilView.as_view(), name='ver'),
    url(r'^(?P<cliente_id>\d+)/eliminar/$', ClienteDeleteView.as_view(), name='eliminar'),
]

cliente/models.py
from django.db import models

# Create your models here.

cliente/forms.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, HTML, Layout
from django.forms import ModelForm
from django.core.exceptions import ValidationError
import re

from proyecto.models import Cliente


class ClienteForm(ModelForm):
    class Meta:
        model = Cliente
        fields = ['ruc', 'nombre', 'direccion', 'pais', 'correo', 'telefono']

    def __init__(self, *args, **kwargs):
        self.success_url = kwargs.pop('success_url')
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        layout = [
            'ruc',
            'nombre',
            'direccion',
            'pais',
            'correo',
            'telefono',
            FormActions(
                Submit('guardar', 'Guardar'),
                HTML('<a class="btn btn-default" href={}>Cancelar</a>'.format(self.success_url)),
            ),
        ]
        self.helper.layout = Layout(*layout)

    def clean_ruc(self):
        ruc = self.cleaned_data['ruc']
        patron = '^[0-9]+$|^[0-9]+-[0-9]$'
        if not re.search(patron, ruc):
            raise ValidationError('Identificador RUC incorrecto');
        else:
            return ruc

    def clean_telefono(self):
        telefono = self.cleaned_data['telefono']
        patron = '^[+]{0,1}[(]{0,1}[0-9]{1,4}[)]{0,1}[-\s\./0-9]*$'
        if not re.search(patron, telefono):
            raise ValidationError('Número de teléfono incorrecto');
        else:
            return telefono

cliente/views.py
from django.http import HttpResponseForbidden, HttpResponse
from django.views.generic import TemplateView, DetailView, UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse, reverse_lazy
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.contrib import messages
from django.conf import settings
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas
from django.views.generic import View
from reportlab.platypus import Table, TableStyle

from cliente.forms import ClienteForm
from proyecto.models import Cliente, Proyecto, UserStory, ESTADOS_US_PROYECTO, MiembroProyecto
from ProyectoIS2_9.utils import cualquier_permiso

class ClienteListView(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    """
    Esta vista se encarga de la página que muestra la lista de clientes. Es necesario
    que el usuario este logueado y tenga cualquier permiso de cliente
    """
    template_name = 'cliente/cliente_list.html'
    permission_required = ('proyecto.add_cliente', 'proyecto.change_cliente', 'proyecto.delete_cliente')
    permission_denied_message = 'No tiene permiso para ver la lista de clientes.'

    def has_permission(self):
        return cualquier_permiso(self.request.user, self.get_permission_required())

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def get_context_data(self, **kwargs):
        context = super(ClienteListView, self).get_context_data(**kwargs)
        context['titulo'] = 'Lista de Clientes'
        context['crear_url'] = reverse('cliente:crear')
        context['crear_button'] = self.request.user.has_perm('proyecto.add_cliente')
        context['crear_button_text'] = 'Nuevo Cliente'

        # datatable
        context['nombres_columnas'] = ['id', 'RUC', 'Nombre', 'Dirección', 'Teléfono']
        context['order'] = [1, 'asc']
        context['datatable_row_link'] = reverse('cliente:ver', args=(1,))  # pasamos inicialmente el id 1
        context['list_json'] = reverse('cliente:lista_json')

        context['breadcrumb'] = [{'nombre':'Inicio', 'url':'/'},
                                 {'nombre':'Clientes', 'url': '#'},]

        return context


class ClienteListJson(LoginRequiredMixin, PermissionRequiredMixin, BaseDatatableView):
    """
    Esta vista retorna la lista de clientes en json para el datatable. Es necesario
    que el usuario este logueado y tenga cualquier permiso de cliente
    """
    model = Cliente
    columns = ['id', 'ruc', 'nombre', 'direccion', 'telefono']
    order_columns = ['id', 'ruc', 'nombre', 'direccion', 'telefono']
    max_display_length = 100
    permission_required = ('proyecto.add_cliente', 'proyecto.change_cliente', 'proyecto.delete_cliente')
    permission_denied_message = 'No tiene permiso para ver la lista de clientes.'

    def has_permission(self):
        return cualquier_permiso(self.request.user, self.get_permission_required())

    def handle_no_permission(self):
        return HttpResponseForbidden()


class ClientePerfilView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    """
    Esta vista se encarga de la página que muestra los datos de un cliente en
    específico. Es necesario que el usuario este logueado y tenga el cualquier
    permiso de cliente
    """
    model = Cliente
    context_object_name = 'cliente'
    template_name = 'cliente/cliente_perfil.html'
    pk_url_kwarg = 'cliente_id'
    permission_required = ('proyecto.add_cliente', 'proyecto.change_cliente', 'proyecto.delete_cliente')
    permission_denied_message = 'No tiene permiso para ver este cliente.'

    def has_permission(self):
        return cualquier_permiso(self.request.user, self.get_permission_required())

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def get_context_data(self, **kwargs):
        context = super(ClientePerfilView, self).get_context_data(**kwargs)
        context['titulo'] = 'Perfil del Cliente'

        context['breadcrumb'] = [{'nombre': 'Inicio', 'url': '/'},
                                 {'nombre': 'Clientes', 'url': reverse('cliente:lista')},
                                 {'nombre': context['cliente'].nombre,'url': '#'}]

        return context


class ClienteCreateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Esta vista permite que un usuario logueado y con el permiso
    'add_cliente' registre un nuevo cliente.
    """
    model = Cliente
    template_name = "cliente/cliente_form.html"
    form_class = ClienteForm
    permission_required = 'proyecto.add_cliente'
    permission_denied_message = 'No tiene permiso para registrar nuevos clientes.'

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def get_success_message(self, cleaned_data):
        return "Cliente '{}' registrado exitosamente.".format(cleaned_data['nombre'])

    def get_success_url(self):
        return reverse('cliente:lista')

    def get_form_kwargs(self):
        kwargs = super(ClienteCreateView, self).get_form_kwargs()
        kwargs.update({'success_url': reverse('cliente:lista'),})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(ClienteCreateView, self).get_context_data(**kwargs)
        context['titulo'] = 'Registrar Cliente'
        context['titulo_form_crear'] = 'Insertar Datos del Nuevo Cliente'

        context['breadcrumb'] = [{'nombre': 'Inicio', 'url': '/'},
                                 {'nombre': 'Clientes', 'url': reverse('cliente:lista')},
                                 {'nombre': 'Nuevo Cliente', 'url': '#'}]

        return context


class ClienteUpdateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Esta vista permite que un usuario logueado y con el permiso
    'change_cliente' actualice los datos básicos de un cliente
    (cuyo id se especifica en la url).
    """
    model = Cliente
    form_class = ClienteForm
    context_object_name = 'cliente'
    template_name = 'cliente/cliente_form.html'
    pk_url_kwarg = 'cliente_id'
    permission_required = 'proyecto.change_cliente'
    permission_denied_message = 'No tiene permiso para editar clientes.'

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def get_success_message(self, cleaned_data):
        return "Cliente '{}' editado exitosamente.".format(cleaned_data['nombre'])

    def get_success_url(self):
        return reverse('cliente:ver', kwargs=self.kwargs)

    def get_form_kwargs(self):
        kwargs = super(ClienteUpdateView, self).get_form_kwargs()
        kwargs.update({
            'success_url': self.get_success_url(),
        })
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(ClienteUpdateView, self).get_context_data(**kwargs)
        context['titulo'] = 'Editar Cliente'
        context['titulo_form_editar'] = 'Datos del Cliente'
        context['titulo_form_editar_nombre'] = context['cliente'].nombre

        context['breadcrumb'] = [{'nombre': 'Inicio', 'url': '/'},
                                 {'nombre': 'Clientes', 'url': reverse('cliente:lista')},
                                 {'nombre': context['cliente'].nombre, 'url': self.get_success_url()},
                                 {'nombre': 'Editar', 'url': '#'},]

        return context


class ClienteDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    """
    Esta vista permite que un usuario logueado y con el permiso
    'delete_cliente' elimine un cliente (cuyo id se especifica
    en la url) de la base de datos. Cuando se invoca con el método
    get retorna una página para confirmar la acción. Cuando se invoca
    con el método post borra el cliente (si se puede).
    """
    model = Cliente
    pk_url_kwarg = 'cliente_id'
    context_object_name = 'cliente'
    permission_required = 'proyecto.delete_cliente'
    permission_denied_message = 'No tiene permiso para eliminar clientes'
    template_name = 'cliente/cliente_confirm_delete.html'
    success_url = reverse_lazy('cliente:lista')

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def get_context_data(self, **kwargs):
        context = super(ClienteDeleteView, self).get_context_data(**kwargs)
        context['titulo'] = 'Eliminar Cliente'
        context['breadcrumb'] = [{'nombre': 'Inicio', 'url': '/'},
                                 {'nombre': 'Clientes', 'url': reverse('cliente:lista')},
                                 {'nombre': context['cliente'].nombre, 'url': reverse('cliente:ver', kwargs=self.kwargs)},
                                 {'nombre': 'Eliminar', 'url': '#'},]
        context['eliminable'] = self.eliminable()
        return context

    def eliminable(self):
        return self.get_object().proyecto_set.all().count() == 0

    def delete(self, request, *args, **kwargs):
        if not self.eliminable():
            return HttpResponseForbidden()
        messages.add_message(request, messages.SUCCESS, 'Cliente eliminado')
        return super().delete(request, *args, **kwargs)


class ReporteClientePDF(View):
    """
    Vista que construye un pdf
    """
    def cabecera(self, pdf):
        # Utilizamos el archivo logo_django.png que está guardado en la carpeta media/imagenes
        archivo_imagen = settings.STATICFILES_DIRS[0] + '/img/logo.png'
        # Definimos el tamaño de la imagen a cargar y las coordenadas correspondientes
        pdf.drawImage(archivo_imagen, 40, 750, 120, 90, preserveAspectRatio=True)

    def get(self, request, *args, **kwargs):
        # Indicamos el tipo de contenido a devolver, en este caso un pdf
        response = HttpResponse(content_type='application/pdf')

cliente/templates/cliente/cliente_confirm_delete.html
{% extends 'layout/layout.html' %}

{% block content %}
    {% block titulo %}
        <div class="bg-light lter b-b wrapper-md col-md-12">
            <h1 class="m-n font-thin h3">{{ titulo }}</h1>
        </div>
    {% endblock %}

    {% block breadcrumbs %}
        {{ block.super }}
    {% endblock %}

    <div class="wrapper-md">
        <div class="well m-t bg-light lt">
            {% if eliminable %}
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-xs-12">
                            <p>Seguro que quiere eliminar el cliente "{{ cliente }}"?</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <button type="submit" class="btn m-b-xs btn-danger btn-addon">
                                <i class="fa fa-check"></i>
                                Confirmar
                            </button>
                            <a href="{% url 'cliente:ver' cliente.id %}">
                                <button type="button" class="btn m-b-xs btn-default btn-addon">
                                    <i class="fa fa-close"></i>
                                    Cancelar
                                </button>
                            </a>
                        </div>
                    </div>
                </form>
            {% else %}
                <div class="row">
                    <div class="col-xs-12">
                        <p>
                            No se puede eliminar el cliente "{{ cliente }}" porque tiene
                            vinculado al menos un proyecto
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <a href="{% url 'cliente:ver' cliente.id %}">
                            <button type="button" class="btn m-b-xs btn-default btn-addon">
                                <i class="fa fa-check"></i>
                                Volver
                            </button>
                        </a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

cliente/templates/cliente/cliente_form.html
{% extends 'change_form.html' %}

cliente/templates/cliente/cliente_list.html
{% extends 'change_list.html' %}

cliente/templates/cliente/cliente_perfil.html
{% extends 'layout/layout.html' %}

{% block content %}
    {% block titulo %}
        <div class="bg-light lter b-b wrapper-md col-md-12">
            <h1 class="m-n font-thin h3">{{ titulo }}</h1>
        </div>
    {% endblock %}

    {% block breadcrumbs %}
        {{ block.super }}
    {% endblock %}

    <div class="wrapper-md">
        <div class="well m-t bg-light lt">
            <div class="row">
                <div class="col-xs-6">
                    <h4>{{ cliente.nombre }}</h4>
                    <p>
                        <strong>RUC: </strong>{{ cliente.ruc }}<br><br>
                        <strong>Dirección: </strong>{{  cliente.direccion }}<br>
                    </p>
                </div>
                <div class="col-xs-6">
                    <h4>&nbsp;</h4>
                    <p>
                        <strong>Correo: </strong>{{ cliente.correo }}<br><br>
                        <strong>Teléfono: </strong>{{ cliente.telefono }}<br><br>
                        <strong>País: </strong>{{ cliente.pais }}<br><br>
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    {% if perms.proyecto.add_proyecto or perms.proyecto.change_proyecto or perms.proyecto.delete_proyecto %}
                        <a href="{% url 'cliente:reporte_cliente' cliente.id%}">
                            <button class="btn m-b-xs btn-default btn-addon ">
                                <i class="fa fa-file-pdf-o"></i>
                                Reporte
                            </button>
                        </a>
                    {% endif %}
                    {% if perms.proyecto.change_cliente %}
                        <a href="{% url 'cliente:editar' cliente.id %}">
                            <button class="btn m-b-xs btn-default btn-addon ">
                                <i class="fa fa-pencil"></i>
                                Editar
                            </button>
                        </a>
                    {% endif %}
                    {% if perms.proyecto.delete_cliente %}
                        <a href="{% url 'cliente:eliminar' cliente.id %}">
                            <button class="btn m-b-xs btn-danger btn-addon ">
                                <i class="fa fa-trash"></i>
                                Eliminar
                            </button>
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}